service: zip-aws

custom:
  deployStage: ${opt:stage, self:provider.stage}
  envVariables: ${file(../env-variables-${self:custom.deployStage}.json)}
  writeEnvVars:
    SERVERLESS_STAGE: ${self:custom.deployStage}
    SERVERLESS_PROJECT: 'export'
    SERVERLESS_SERVICE_NAME: ${self:service}

plugins:
- serverless-plugin-write-env-vars

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
          - "s3:*"
          - "dynamodb:*"
          - "lambda:*"
       Resource: "*"
  role: arn:aws:iam::830321976775:role/lambda-vpc-execution-role
functions:
  zip:
    description: Comprime archivos en AWS S3 y notifica cuando finaliza
    handler: handler.zip
    timeout: 900
package:
  exclude:
    - .npmignore
    - config/**
    - package.json
    - README.md
    - slslocal.sh
    - tsconfig.json
    - events/**
    - '*.bat'
    - '*.ts'
    - '**/*.ts'
    - 'src/dev/**'
    - node_modules/aws-sdk/**
    - node_modules/base64-js/**
    - node_modules/buffer/**
    - node_modules/crypto-browserify/**
    - node_modules/ieee754/**
    - node_modules/isarray/**
    - node_modules/jmespath/**
    - node_modules/punycode/**
    - node_modules/querystring/**
    - node_modules/sax/**
    - node_modules/url/**
    - node_modules/xml2js/**
    - node_modules/xmlbuilder/**
